INSERT INTO WISHLIST (LISTID, WISHERNAME,EVENTNAME) VALUES (1, 'JOAKIM', '12 ÅRS FØDSELSDAG');
INSERT INTO WISHLIST (LISTID, WISHERNAME,EVENTNAME) VALUES (2, 'MARKUS', '3,5 ÅRS FØDSELSDAG');
INSERT INTO WISHLIST (LISTID, WISHERNAME,EVENTNAME) VALUES (3, 'AUGUST', 'KONFIRMATION');


INSERT INTO WISH (WISHID, NAME, DESCRIPTION,ITEMURL,PRICE, LISTID) VALUES (1, 'AirPods', 'De der seje airpods max', 'www.apple.com', 4599, 2);
INSERT INTO WISH (WISHID, NAME, DESCRIPTION,ITEMURL,PRICE, LISTID) VALUES (2, 'Oplader', 'En MacBook air oplader', 'www.apple.com', 199, 1);
INSERT INTO WISH (WISHID, NAME, DESCRIPTION,ITEMURL,PRICE, LISTID) VALUES (3, 'Rolex', 'Et datejust', 'www.rolex.com', 45999, 3);

INSERT INTO IMAGE(IMAGEID,IMAGE,WISHID) VALUES (1, 'WWW.GOOGLE.COM',1);
INSERT INTO IMAGE(IMAGEID,IMAGE,WISHID) VALUES (2, 'WWW.GOOGLE.COM',2);
INSERT INTO IMAGE(IMAGEID,IMAGE,WISHID) VALUES (3, 'WWW.GOOGLE.COM',3);